### ISSUE TITLE
apexchart

### ISSUE THREAD

**Issue by Poopikakas** [TypQxQ/Sigenergy-Home-Assistant-Integration#12]
Hi, like you new sigenergy integration.
im now using it but the new apexchart is giving me problems. it only shows down to 30öre and nothing below that.
![Skärmbild 2024-09-26 125056](https://github.com/user-attachments/assets/c1647af7-b216-4562-9eea-bc8a4558e756)
best regards Erik

**Comment by TypQxQ** [comment]
Hi Erik! 

Try the newer version. The new code has dynamic chart cutoff. 
For this, it should be at around -3 öre today.

Hälsningar
Andrei

**Comment by Poopikakas** [comment]
that did it :-) missed that you had published new verisions. thanks
