### ISSUE TITLE
Errors in modbus_signergy.yaml

### ISSUE THREAD

**Issue by arm-dkm** [TypQxQ/Sigenergy-Home-Assistant-Integration#14]
I'm seeing a number of errors in the Studio Code Server integration in Home Assistant in the modbus_signergy.yaml.

These are all in the automation section, and specifically for every action therein. An example is below:

...
    action:
      - action: modbus.write_register
...

The error "Property action is not allowed" suggests that there might be a syntax issue or a misconfiguration. In Home Assistant automations, the correct key for actions is service, not action. So this should be:

...
    action:
      - service: modbus.write_register
...

**Comment by TypQxQ** [comment]
Looks fine on my setup:
![image](https://github.com/user-attachments/assets/8c1658cd-03c9-4a62-b59b-2f91d292a915)
Regards, Andrei

**Comment by arm-dkm** [comment]
Hmmm... so here's what I see...

![image](https://github.com/user-attachments/assets/dce5bb42-1631-40e9-862b-14a6bc7680e1)

I'm wondering whether this is a difference in HA versions?

![image](https://github.com/user-attachments/assets/9641a4fe-4bb4-4075-a06b-3d699d3197b6)

**Comment by koddistortion** [comment]
https://www.home-assistant.io/blog/2024/08/07/release-20248/#goodbye-service-calls-hello-actions-

Home Assistant changed service to Action with Release  of 2024.08

**Comment by arm-dkm** [comment]
Therefore I'm guessing there's some error/regression in 2024.9.3 since that's what I'm running, as that's later than 2024.08?

**Comment by arm-dkm** [comment]
I'm going to close this as it's obviously not an issue with the integration, it's either HA or the Studio Code Server integrarion.

**Comment by TypQxQ** [comment]
I upgraded to 2024.9.3 and can't see this error.
Check to see if you have the right Language Mode:
![image](https://github.com/user-attachments/assets/93092c3a-60d9-4ca2-8142-fed154ac3e44)

And latest VSCode:
![image](https://github.com/user-attachments/assets/805027f8-db6f-42b4-9325-f330caf23e91)
