### ISSUE TITLE
Reduce update time

### ISSUE THREAD

**Issue by AlexJacu** [TypQxQ/Sigenergy-Home-Assistant-Integration#16]
I would like to reduce the pdate from 5 sec. to 1 min.
i didn't find an setting to do so.

**Comment by TypQxQ** [comment]
Hi! What update timer would you like to reduce?

**Comment by TypQxQ** [comment]
If it's Sigenergy Modbus, then update scan_interval parameter. It's at 10s on the most frequently updated settings.
The charts are dependent of the sensors updating.
