### ISSUE TITLE
Modbus scale values

### ISSUE THREAD

**Issue by JuergenOrth** [TypQxQ/Sigenergy-Home-Assistant-Integration#23]
I found that (at least) 2 scale values in modbus_sigenergy.yml differ from API description.
These are:

- Reg 30604 ESS average cell voltage
- Reg 31000 Rated grid voltage

I changed it accordingly in my local config:

```
root@pi51:~/docker/ha/config/packages# diff /tmp/modbus_sigenergy.yaml .
954c954
<         scale: 0.01
---
>         scale: 0.001
1003c1003
<         scale: 0.01
---
>         scale: 0.1
```

**Comment by TypQxQ** [comment]
Thank you! I tried to check this untill I got crosseyed 😆 so I might have missed something else too.
Thanx for finding this, it's now fixed.

Regards,
Andrei
