### ISSUE TITLE
Some more scale deviations in modbus_sigenergy.yaml

### ISSUE THREAD

**Issue by JuergenOrth** [TypQxQ/Sigenergy-Home-Assistant-Integration#24]
Finally I checked all scale values for sensors in modbus_sigernergy.yaml and found differences for following registers:

- 31023
- 40014
- 40016
- 40018

All of them should have 0.001 for scale as the gain is documented as 1000 in API documentation. This also may impact the "precision" param.

**Comment by TypQxQ** [comment]
Thank you! I will try to fix this later today 😄

**Comment by TypQxQ** [comment]
I've updated this sensors now:
Sigen Power factor
Sigen Phase A reactive power fixed adjustment target value
Sigen Phase B reactive power fixed adjustment target value
Sigen Phase C reactive power fixed adjustment target value
